### ISSUE TITLE
com.dynatrace.sdk.server.exceptions.ServerResponseException: System profile 'null' not found

### ISSUE THREAD

**Issue by SonjaChevre** [jenkinsci/dynatrace-plugin#1]
from Mike V:

so I was running into issues with my new build fetching results via the plugin so I went back to the old trusty SimpleWebApp-Ant from ages ago. Even that appears to be failing to fetch results...
 
com.dynatrace.sdk.server.exceptions.ServerResponseException: System profile 'null' not found
 
Looking at dt server logs it really appears the jenkins plugin is trying to hit the rest api using the profile name of null:
 
2016-09-15 20:10:30 WARNING [XmlRestManagementService] System profile 'null' not found
 
 
I'm kind of pulling my hair out over here, everything is pretty up to date (jenkins 2.7.3, dT jenkins plugin v2.0.4, dt 6.3.9, etc), in fact, perhaps  I am too up to date?

FYI, downgraded to 2.0.3 of the jenkins plugin and things seem to work...

**Comment by akirasoft** [comment]
thanks for submitting this on my behalf Sonja. Please let me know if there is any information I can submit to ease troubleshooting/reproduction of this issue.

**Comment by knecel** [comment]
Fixed by commit b54828f30d50f480330966e47fe7da4d44dc0169 (release 2.0.5).
