### ISSUE TITLE
Report collection timeout

### ISSUE THREAD

**Issue by Harriebo** [jenkinsci/dynatrace-plugin#11]
We have been using dynatrace jenkins integration for a while, after our latest updates to the new Jenkins and Dynatrace 7 and our test frame work to JUnit5 we are getting timeouts on reports collection:

Finishing test run with ID=d7a0c4a9-0754-4d49-a119-5f4c2ecb5fc0
Finishing test run with ID=36ea96cb-430d-4a29-8a99-2b9e9b00b3f4
Sleeping for the configured delay of 120 seconds before retrieving test run data from Dynatrace Server...
Connecting to Dynatrace Server REST interface... (ID=d7a0c4a9-0754-4d49-a119-5f4c2ecb5fc0)
Sleeping for the configured delay of 120 seconds before retrieving test run data from Dynatrace Server... re-try 1 out of 3
Connecting to Dynatrace Server REST interface... (ID=d7a0c4a9-0754-4d49-a119-5f4c2ecb5fc0)
Sleeping for the configured delay of 120 seconds before retrieving test run data from Dynatrace Server... re-try 2 out of 3
Connecting to Dynatrace Server REST interface... (ID=d7a0c4a9-0754-4d49-a119-5f4c2ecb5fc0)
Sleeping for the configured delay of 120 seconds before retrieving test run data from Dynatrace Server... re-try 3 out of 3
Connecting to Dynatrace Server REST interface... (ID=d7a0c4a9-0754-4d49-a119-5f4c2ecb5fc0)
Connecting to Dynatrace Server REST interface... (ID=36ea96cb-430d-4a29-8a99-2b9e9b00b3f4)
Report summary: {Failed=0, Degraded=0, Volatile=0, Improved=0, Passed=0}.

We have tried upping the collection timeout until 10 min. but that even did not help. Any suggestions on how to solve this issue? We found one example which was fixed by putting a performance warehouse and upping the timeout, but we already have both and still it will not report any test results.

The collector seem to be running a lot a exactly 100% while there are 4 cpu's available. But I did not found the option jet to specify multiple collectors for one build and test cycle and I am also not sure if that really is the problem.

The collector log states:
2017-11-15 13:34:57 WARNING [AgentCenter] Agent "Surefire_Jenkins@dci11:7689" (7c16c221) was shut down as a result of an overdue event time.
2017-11-15 13:34:57 WARNING [AgentCenter] Agent "Surefire_Jenkins@dci11:7725" (6b5221bb) was shut down as a result of an overdue event time.
2017-11-15 13:34:57 WARNING [AgentCenter] Agent "Surefire_Jenkins@dci11:7156" (e24ade8f) was shut down as a result of an overdue event time.
2017-11-15 13:34:57 WARNING [AgentCenter] Agent "Surefire_Jenkins@dci8:7005" (5903ff78) was shut down as a result of an overdue event time.
2017-11-15 13:34:57 WARNING [AgentCenter] Agent "Surefire_Jenkins@dci8:6411" (ffcd8660) was shut down as a result of an overdue event time.

**Comment by dglugla** [comment]
Hi @Harriebo 
Could you please provide AppMon Server logs, or even the whole support archive, as described [here](https://www.dynatrace.com/support/doc/appmon/application-monitoring/appmon-client/dashlets/system-information-dashlet/#create-a-support-archive).
It's important to cover the test execution timeframe, so we could analyze what happens on the server side.
Please also consider creating support ticket: https://support.dynatrace.com which gives us additional info e.g.about your license.

Thanks, Darek

**Comment by Harriebo** [comment]
Of course, I was already doubting if this was the plugin or the new release, Ill create a support ticket.
